url: https://jclouds.apache.org
title: Apache jclouds
markdown: kramdown
pygments: true
plugins: [jekyll-paginate]
paginate: 5
paginate_path: "blog/page:num"
permalink: /blog/:categories/:year/:month/:day/:title
relative_permalinks: false
latest_version: 2.7.0
latest_version_date: 2025-01-29
latest_snapshot: 2.7.1-SNAPSHOT
